replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

lifecycle: {}
#  postStart:
#    exec:
#      command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
#  preStop:
#    exec:
#      command: ["/bin/sh","-c","/opt/lifecycle/prestop.sh"]

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: api.wework.cn
      paths: ['/test1','/test2']
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

env:
  - name: test
    value: 123
  - name: test1
    valueFrom:
      secretKeyRef:
        name: demo-s
        key: test1

ports:
  - name: api
    containerPort: 80
  #- name: api
  #  containerPort: 80
#启动探针，10*20=200s，超时后自动执行重启策略
startupProbe:
  tcpSocket:
    port: api
  initialDelaySeconds: 0
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 20
#存活探针
livenessProbe:
  httpGet:
    path: /
    port: api
  initialDelaySeconds: 0
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 2
#就绪探针
readinessProbe:
  httpGet:
    path: /
    port: api
  initialDelaySeconds: 0
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 2



resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
